name             'iis_test'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures iis_test'
long_description 'Installs/Configures iis_test'
version          '0.1.3'
depends 'windows'
depends 'iis'
